dist: xenial

sudo: required

language: php

notifications:
  email: false

php:
  - '7.0'
  - '7.1'
  - '7.2'
  - nightly

matrix:
  fast_finish: true

#  allow_failures:
#    - php: nightly

services:
  - mysql

cache:
  apt: true
  directories:
    - vendor
    - $HOME/.composer/cache/files

#addons:
#
# apt:
#    
#    sources:
#
#     - ppa:ondrej/apache2
#
#    packages:
#
#      - php7.2
#      - php7.2-fpm
#      - php7.2-mysql
#      - nginx

  hosts:
    - site.localhost
    - test1.site.localhost

env:
  global:
    - SITE_URL="http://site.localhost"
    - SITE_DOMAIN="site.localhost"
    - DB_NAME="test"

before_install:
  - mysql -e "create database IF NOT EXISTS $DB_NAME;" -uroot
  - sudo apt-get install software-properties-common python-software-properties -y
  - sudo add-apt-repository -y ppa:ondrej/php
  - sudo apt-get update
  - sudo apt-get install php7.2-curl php7.2-gd php7.2-json php7.2-mbstring php7.2-intl php7.2-mysql php7.2-xml php7.2-zip nginx php7.2-fpm -y

install:
  - composer install --prefer-dist

  # copy the Nginx configuration file for the site among the available ones from 
  # the `build` folder; the content of the Nginx configuration file I'm using is
  # specific to WordPress (see below) so use whatever you need to use.
  # Given the current environment configuration it will be copied to `/etc/nginx/sites-available/site.localhost`
  - sudo cp build/travis-nginx-conf /etc/nginx/sites-available/$SITE_DOMAIN

  # using sed replace the placeholder text in the Nginx configuration file to use the
  # correct site folder path and domain
  - sudo sed -e "s?%TRAVIS_BUILD_DIR%?$TRAVIS_BUILD_DIR?g" --in-place /etc/nginx/sites-available/$SITE_DOMAIN
  - sudo sed -e "s?%SITE_DOMAIN%?$SITE_DOMAIN?g" --in-place /etc/nginx/sites-available/$SITE_DOMAIN

  # enable the site by creating a symbolic link in the `sites-enabled` folder
  - sudo ln -s /etc/nginx/sites-available/$SITE_DOMAIN /etc/nginx/sites-enabled/

before_script:

  # restart Nginx and PHP-FPM services to make sure the new site is loaded
  - sudo service php7.2-fpm restart
  - sudo service nginx restart

script:
  # finally run the tests...
  - curl http://site.localhost
